modLoader="javafml"
loaderVersion="[39,)"
license="The Apache License, Version 2.0"
issueTrackerURL=""

[[mods]]
modId="excavar"
version="${file.jarVersion}"
displayName="Excavar"
displayURL="https://assets.melanx.de/updates/excavar.json"
authors="MelanX"
description="""
A lightweight excavation mod for modern Minecraft versions
"""

[[dependencies.excavar]]
    modId="forge"
    mandatory=true
    versionRange="[39.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.excavar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"

