modLoader="javafml"
loaderVersion="[46,)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/Excavar/issues"

[[mods]]
modId="excavar"
version="${version}"
displayName="Excavar"
displayURL="https://assets.melanx.de/updates/excavar.json"
authors="MelanX"
description="""
A lightweight excavation mod for modern Minecraft versions
"""

[[dependencies.excavar]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.excavar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20, 1.21)"
    ordering="NONE"
    side="BOTH"
