modLoader="javafml"
loaderVersion="[36,)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/Excavar/issues"

[[mods]]
modId="excavar"
version="${file.jarVersion}"
displayName="Excavar"
displayURL="https://assets.melanx.de/updates/excavar.json"
authors="MelanX"
description="""
A lightweight excavation mod for modern Minecraft versions
"""

[[dependencies.excavar]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.20,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.excavar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5, 1.17)"
    ordering="NONE"
    side="BOTH"

