modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/ChaoticTrials/Excavar/issues"

[[mods]]
modId="excavar"
version="${mod_version}"
displayName="Excavar"
updateJSONURL="https://assets.melanx.de/updates/excavar.json"
displayURL="https://modrinth.com/user/MelanX"
authors="MelanX"
description="""
A lightweight excavation mod for modern Minecraft versions
"""

[[dependencies.${modid}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"
